version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: houstonrice2024
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# Install the docker dmg and make sure to add this to ~/.zprofile `export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin/"